"""Post-publication verifier tests.

The verifier is prepared, not executed against the IETF. These tests drive it
entirely from saved records, and assert that it refuses to overclaim byte
identity for representations the IETF regenerates.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import support  # noqa: E402  (path setup)
import verify_published as verifier  # noqa: E402

IDENTITY = "draft-sergeev-wexp-core-01"
SUBMITTED_DIGEST = "a" * 64


def bundle(identity: str = IDENTITY, digest: str = SUBMITTED_DIGEST) -> dict:
    return {"artifact_identity": identity, "submission_xml": {"sha256": digest}}


def record(**overrides) -> dict:
    value = {
        "observed_at_source": {"document_url": "https://example.invalid/doc"},
        "document": {
            "name": "draft-sergeev-wexp-core",
            "rev": "01",
            "time": "2026-09-01T10:00:00Z",
            "submissions": ["/api/v1/submit/submission/999/"],
            "states": ["/api/v1/doc/state/1/"],
        },
        "published_xml_sha256": SUBMITTED_DIGEST,
    }
    value.update(overrides)
    return value


class TestVerification(unittest.TestCase):
    def test_matching_publication_verifies(self) -> None:
        result = verifier.verify(bundle(), record(), label="CORE-01")
        self.assertEqual(result.terminal, "CORE-01 IETF PUBLICATION VERIFIED")
        self.assertEqual(result.observations["xml_relationship"], "BYTE_IDENTICAL")

    def test_wrong_draft_name_is_a_mismatch(self) -> None:
        observed = record()
        observed["document"]["name"] = "draft-someone-else-wexp-core"
        result = verifier.verify(bundle(), observed, label="CORE-01")
        self.assertTrue(result.terminal.startswith("IETF PUBLICATION MISMATCH —"))
        self.assertIn("V02", result.terminal)

    def test_wrong_revision_is_a_mismatch(self) -> None:
        observed = record()
        observed["document"]["rev"] = "02"
        result = verifier.verify(bundle(), observed, label="CORE-01")
        self.assertIn("V03", result.terminal)

    def test_absent_record_is_a_mismatch_rather_than_a_pass(self) -> None:
        result = verifier.verify(bundle(), {"document": {}}, label="CORE-01")
        self.assertIn("V01", result.terminal)

    def test_differing_archived_xml_is_reported_without_claiming_identity(self) -> None:
        observed = record(published_xml_sha256="b" * 64)
        result = verifier.verify(bundle(), observed, label="CORE-01")
        self.assertEqual(result.observations["xml_relationship"], "NOT_PROVEN_IDENTICAL")
        # A regenerated archive copy is a legitimate outcome, so V04 states the
        # relationship exactly rather than failing.
        self.assertNotIn("V04", result.terminal)
        detail = next(check.detail for check in result.checks if check.check_id == "V04")
        self.assertIn("REGENERATED or ALTERED", detail)

    def test_absent_archived_xml_is_a_mismatch(self) -> None:
        observed = record()
        del observed["published_xml_sha256"]
        result = verifier.verify(bundle(), observed, label="CORE-01")
        self.assertIn("V04", result.terminal)

    def test_missing_submission_identifiers_are_a_mismatch(self) -> None:
        observed = record()
        observed["document"]["submissions"] = []
        result = verifier.verify(bundle(), observed, label="CORE-01")
        self.assertIn("V06", result.terminal)

    def test_non_claims_are_recorded(self) -> None:
        result = verifier.verify(bundle(), record(), label="CORE-01")
        joined = " ".join(result.observations["non_claims"])
        self.assertIn("regenerated by IETF tooling", joined)
        self.assertIn("not IETF acceptance", joined)

    def test_label_defaults_to_the_revision_identity(self) -> None:
        result = verifier.verify(bundle(), record())
        self.assertEqual(result.terminal, "CORE-01 IETF PUBLICATION VERIFIED")


class TestNormalization(unittest.TestCase):
    def test_pagination_and_whitespace_are_normalized(self) -> None:
        paginated = "line one\n\fInternet-Draft   WEXP   September 2026\nline two\n"
        self.assertEqual(verifier.normalize_text(paginated), "line one line two")


class TestNoNetworkByDefault(unittest.TestCase):
    def test_offline_run_without_a_record_refuses(self) -> None:
        manifest = support.REPO_ROOT / "publication" / "authorizations" / "draft-sergeev-wexp-core-00.json"
        code = verifier.main(["--bundle-manifest", str(manifest)])
        self.assertEqual(code, 1)


if __name__ == "__main__":
    unittest.main()
