#!/usr/bin/env python3
"""Post-publication verification (design + implementation; not executed as part
of pipeline preparation).

After a revision has actually been submitted, confirmed by a human, and
announced, this compares what the IETF published against what was authorized
and submitted.

Read-only Datatracker/IETF endpoints observed 2026-08-14:

* ``GET https://datatracker.ietf.org/api/v1/doc/document/<draft-name>/?format=json``
  returns ``name``, ``rev``, ``title``, ``time``, ``pages``, ``states``,
  ``submissions``;
* ``GET https://www.ietf.org/archive/id/<draft-name>-<rev>.xml`` returns the
  archived XML for the revision.

Honesty constraints built into the comparison:

* the archived XML is compared byte-for-byte against the submitted bytes and
  reported as ``BYTE_IDENTICAL`` or ``REGENERATED`` — never assumed;
* rendered text/HTML are regenerated by IETF tooling, so they are compared
  semantically (normalized) and never claimed to be byte-identical;
* a missing or ambiguous field is a mismatch, not a pass.

Default mode is offline and consumes a saved record, so the verifier is fully
testable without contacting the IETF.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))

import publication_guard as guard  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
DATATRACKER_DOC_URL = "https://datatracker.ietf.org/api/v1/doc/document/{name}/?format=json"
IETF_ARCHIVE_XML_URL = "https://www.ietf.org/archive/id/{name}-{rev}.xml"

VERIFIED_SUFFIX = "IETF PUBLICATION VERIFIED"
MISMATCH_PREFIX = "IETF PUBLICATION MISMATCH"


@dataclass(frozen=True)
class VerificationResult:
    label: str
    checks: tuple[guard.CheckResult, ...]
    observations: dict[str, Any]

    @property
    def mismatches(self) -> tuple[guard.CheckResult, ...]:
        return tuple(check for check in self.checks if check.status != guard.PASS)

    @property
    def terminal(self) -> str:
        if not self.mismatches:
            return f"{self.label} {VERIFIED_SUFFIX}"
        detail = "; ".join(f"{check.check_id}: {check.detail}" for check in self.mismatches)
        return f"{MISMATCH_PREFIX} — {detail}"

    def as_dict(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "terminal_result": self.terminal,
            "checks": [check.as_dict() for check in self.checks],
            "observations": self.observations,
        }


def fetch_record(name: str, rev: str, *, timeout: float = 60.0) -> dict[str, Any]:
    """Fetch the live Datatracker record and archived XML. Network-only path."""

    import urllib.request

    document_url = DATATRACKER_DOC_URL.format(name=name)
    with urllib.request.urlopen(document_url, timeout=timeout) as response:
        document = json.loads(response.read().decode("utf-8"))

    xml_url = IETF_ARCHIVE_XML_URL.format(name=name, rev=rev)
    with urllib.request.urlopen(xml_url, timeout=timeout) as response:
        published_xml = response.read()

    return {
        "observed_at_source": {"document_url": document_url, "xml_url": xml_url},
        "document": document,
        "published_xml_sha256": hashlib.sha256(published_xml).hexdigest(),
        "published_xml_size_bytes": len(published_xml),
    }


def normalize_text(value: str) -> str:
    """Collapse the whitespace and pagination IETF tooling legitimately alters."""

    without_pagination = re.sub(r"\f[^\n]*\n", "\n", value)
    return re.sub(r"\s+", " ", without_pagination).strip()


def verify(
    bundle_manifest: dict[str, Any],
    record: dict[str, Any],
    *,
    label: str | None = None,
) -> VerificationResult:
    """Compare an exact Phase-A bundle against an observed publication record."""

    identity = str(bundle_manifest.get("artifact_identity") or "")
    match = re.fullmatch(r"(?P<name>draft-[a-z0-9-]+)-(?P<rev>[0-9]{2})", identity)
    expected_name = match.group("name") if match else ""
    expected_rev = match.group("rev") if match else ""
    resolved_label = label or (identity.split("-")[-2:] and "-".join(identity.split("-")[-2:]).upper())

    document = record.get("document") or {}
    checks: list[guard.CheckResult] = []

    def check(check_id: str, title: str, ok: bool, detail: str) -> None:
        checks.append(
            guard.CheckResult(check_id, title, guard.PASS if ok else guard.FAIL, detail)
        )

    check(
        "V01",
        "a Datatracker record exists for the submitted revision",
        bool(document.get("name")),
        f"document.name={document.get('name')!r}",
    )
    check(
        "V02",
        "published draft name matches the authorized identity",
        document.get("name") == expected_name and bool(expected_name),
        f"published {document.get('name')!r} vs authorized {expected_name!r}",
    )
    check(
        "V03",
        "published revision matches the authorized revision",
        document.get("rev") == expected_rev and bool(expected_rev),
        f"published {document.get('rev')!r} vs authorized {expected_rev!r}",
    )

    submitted = (bundle_manifest.get("submission_xml") or {}).get("sha256")
    published = record.get("published_xml_sha256")
    byte_identical = bool(submitted) and submitted == published
    checks.append(
        guard.CheckResult(
            "V04",
            "archived XML relationship to the submitted bytes is stated exactly",
            guard.PASS if published else guard.FAIL,
            (
                f"BYTE_IDENTICAL (sha256={published})"
                if byte_identical
                else (
                    f"REGENERATED or ALTERED: submitted {submitted}, archived {published}"
                    if published
                    else "no archived XML digest was observed"
                )
            ),
        )
    )

    timestamp = document.get("time")
    check("V05", "publication timestamp is recorded", bool(timestamp), f"time={timestamp!r}")
    submissions = document.get("submissions")
    check(
        "V06",
        "Datatracker submission identifiers are recorded",
        isinstance(submissions, list) and bool(submissions),
        f"submissions={submissions!r}",
    )
    check(
        "V07",
        "document states are recorded",
        bool(document.get("states")),
        f"states={document.get('states')!r}",
    )

    observations = {
        "authorized_identity": identity,
        "submitted_xml_sha256": submitted,
        "published_xml_sha256": published,
        "xml_relationship": "BYTE_IDENTICAL" if byte_identical else "NOT_PROVEN_IDENTICAL",
        "datatracker_time": timestamp,
        "datatracker_submissions": submissions,
        "datatracker_states": document.get("states"),
        "source_urls": record.get("observed_at_source"),
        "non_claims": [
            "Rendered text and HTML are regenerated by IETF tooling and are not "
            "claimed to be byte-identical to any locally rendered form.",
            "A verified publication record is not IETF acceptance, working group "
            "adoption, or evidence of protocol correctness.",
        ],
    }
    return VerificationResult(
        label=str(resolved_label or identity.upper()),
        checks=tuple(checks),
        observations=observations,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-manifest", type=Path, required=True)
    parser.add_argument(
        "--record",
        type=Path,
        default=None,
        help="saved publication record; required unless --online is given",
    )
    parser.add_argument(
        "--online",
        action="store_true",
        help="fetch the live Datatracker record (read-only; not run during pipeline preparation)",
    )
    parser.add_argument("--label", default=None, help="e.g. CORE-01")
    parser.add_argument("--json", dest="json_out", type=Path, default=None)
    args = parser.parse_args(argv)

    manifest = json.loads(args.bundle_manifest.read_text(encoding="utf-8"))
    if args.online:
        identity = str(manifest.get("artifact_identity") or "")
        match = re.fullmatch(r"(?P<name>draft-[a-z0-9-]+)-(?P<rev>[0-9]{2})", identity)
        if not match:
            print(f"{MISMATCH_PREFIX} — bundle artifact_identity is malformed: {identity!r}")
            return 1
        record = fetch_record(match.group("name"), match.group("rev"))
    elif args.record is not None:
        record = json.loads(args.record.read_text(encoding="utf-8"))
    else:
        print(f"{MISMATCH_PREFIX} — no publication record supplied and --online was not given")
        return 1

    result = verify(manifest, record, label=args.label)
    for check in result.checks:
        print(f"{check.status}: {check.check_id} {check.title}: {check.detail}")
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(result.as_dict(), indent=2) + "\n", encoding="utf-8")
    print(result.terminal)
    return 0 if not result.mismatches else 1


if __name__ == "__main__":
    raise SystemExit(main())
