#!/usr/bin/env python3
"""Regenerate the hash-pinned Python toolchain lock from ``tools/toolchain.json``.

The lock exists so that provisioning the draft toolchain never depends on
whatever happens to be installed on a developer machine. Every distribution pip
downloads must match a hash recorded here, and pip refuses the whole install if
any requirement lacks one.

Run this only when a pinned version in ``toolchain.json`` changes:

    python3 tools/refresh_toolchain_lock.py

It queries the public PyPI JSON API for every pinned ``name==version`` and
records the SHA-256 of every distribution published for that exact version, so
the lock is valid on any platform rather than only the one that generated it.
Network access is required; the provisioning script itself never calls this.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECLARATION = ROOT / "tools" / "toolchain.json"
LOCK = ROOT / "tools" / "python-toolchain.lock"
PYPI_JSON = "https://pypi.org/pypi/{name}/{version}/json"

HEADER = """\
# Generated by tools/refresh_toolchain_lock.py from tools/toolchain.json.
# Do not edit by hand.
#
# Hash-pinned requirements for the wexp-spec IETF draft toolchain. Install with:
#
#     python3 scripts/provision_toolchain.py
#
# which runs pip with --require-hashes, so an unpinned or tampered distribution
# aborts the install rather than silently producing a different renderer.
#
# Every SHA-256 published for each pinned version is listed, so this lock is
# valid on any platform, not only the one that generated it.
"""


def distribution_hashes(name: str, version: str, *, timeout: float = 60.0) -> list[str]:
    with urllib.request.urlopen(PYPI_JSON.format(name=name, version=version), timeout=timeout) as response:
        payload = json.load(response)
    hashes = sorted({entry["digests"]["sha256"] for entry in payload["urls"]})
    if not hashes:
        raise SystemExit(f"{name}=={version}: PyPI lists no distributions")
    return hashes


def render(packages: dict[str, str]) -> str:
    lines = [HEADER]
    for name in sorted(packages, key=str.lower):
        version = packages[name]
        hashes = distribution_hashes(name, version)
        entry = [f"{name}=={version}"]
        entry.extend(f"    --hash=sha256:{value}" for value in hashes)
        lines.append(" \\\n".join(entry))
        print(f"{name}=={version}: {len(hashes)} distribution(s)", file=sys.stderr)
    return "\n".join(lines) + "\n"


def main() -> int:
    declaration = json.loads(DECLARATION.read_text(encoding="utf-8"))
    packages = declaration["python_packages"]
    if not isinstance(packages, dict) or not packages:
        raise SystemExit(f"{DECLARATION}: python_packages must be a non-empty object")
    LOCK.write_text(render(packages), encoding="utf-8")
    print(f"wrote {LOCK.relative_to(ROOT)} for {len(packages)} package(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
